apiVersion: v1
kind: ConfigMap
metadata:
  name: clearing-service-config
  namespace: payment-processor
data:
  SPRING_APPLICATION_NAME: "clearing-service"
  SERVER_PORT: "8089"
  TRACING_SAMPLING_PROBABILITY: "0.1"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  DB_URL: "jdbc:postgresql://postgres:5432/clearingservicedb"
  DB_USERNAME: "postgres"
  DB_USER: "postgres"
